keyframe:
- bbox_ratios:
  - 0.0
  - 0.55
  - 0.3
  - 0.65
  frame: 0
  prompt: A colorful parrots walking on the beach
- bbox_ratios:
  - 0.3
  - 0.55
  - 0.6
  - 0.65
  frame: 4
  prompt: A colorful parrots walking on the beach
- bbox_ratios:
  - 0.4
  - 0.35
  - 0.7
  - 0.65
  frame: 12
  prompt: a king penguin walking on the beach
- bbox_ratios:
  - 0.7
  - 0.35
  - 1.0
  - 0.65
  frame: 24
  prompt: a king penguin walking on the beach
seed: 123451232578
token_inds:
- 1
- 2
- 3
width: 512
height: 512
num_inference_steps:
trailblazer:
  num_dd_spatial_steps: 3
  num_dd_temporal_steps: 3
  spatial_strengthen_scale: 0.25
  spatial_weaken_scale: 0.01
  temp_strengthen_scale: 0.25
  temp_weaken_scale: 0.01
  trailing_length: 10
