# See the line92 - line95 in genreate.py for how Peekaboo generating bbox
keyframe:
- bbox_ratios:
  - 0.8
  - 0.35
  - 1.0
  - 0.65
  frame: 0
  prompt: A yellow dog running on the grass
- bbox_ratios:
  - 0.6
  - 0.35
  - 0.8
  - 0.65
  frame: 24
  prompt: A yellow dog running on the grass
token_inds:
- 1
- 2
- 3
width: 512
height: 512
num_inference_steps:
seed: 2
trailblazer:
  num_dd_spatial_steps: 5
  num_dd_temporal_steps: 5
  spatial_strengthen_scale: 0.5
  spatial_weaken_scale: 0.05
  temp_strengthen_scale: 0.5
  temp_weaken_scale: 0.05
  trailing_length: 4
