keyframe:
- bbox_ratios:
  - 0.5
  - 0.35
  - 1.0
  - 0.65
  frame: 0
  prompt: A clown fish swimming in a coral reef
- bbox_ratios:
  - 0.0
  - 0.35
  - 0.5
  - 0.65
  frame: 24
  prompt: A clown fish swimming in a coral reef
num_dd_spatial_steps: 5
num_dd_temporal_steps: 5
num_frames: 24
seed: 123451232531
spatial_strengthen_scale: 0.1
spatial_weaken_scale: 0.001
temp_strengthen_scale: 0.1
temp_weaken_scale: 0.001
token_inds:
- 1
- 2
- 3
trailing_length: 15
