keyframe:
- bbox_ratios:
  - 0.14
  - 0.13
  - 0.34
  - 0.75
  frame: 0
  prompt: A panda eating bamboo in a lush bamboo forest
- bbox_ratios:
  - 0.14
  - 0.13
  - 0.34
  - 0.75
  frame: 24
  prompt: A panda eating bamboo in a lush bamboo forest
seed: 2
token_inds:
- 2
width: 576
height: 320
num_inference_steps: 50
trailblazer:
  num_dd_spatial_steps: 5
  num_dd_temporal_steps: 5
  spatial_strengthen_scale: 0.15
  spatial_weaken_scale: 0.001
  temp_strengthen_scale: 0.15
  temp_weaken_scale: 0.001
  trailing_length: 13
text2vidzero:
  motion_field_strength_x: 8
  motion_field_strength_y: 0
peekaboo:
  frozen_steps: 2
