# bbox_ratios: left, top, bottom, right
keyframe:
- bbox_ratios:
  - 0.0
  - 0.35
  - 0.4
  - 0.65
  frame: 0
  prompt: A cheetah is running on the grass
- bbox_ratios:
  - 0.6
  - 0.35
  - 1.0
  - 0.65
  frame: 6
  prompt: A cheetah is running on the grass
- bbox_ratios:
  - 0.0
  - 0.35
  - 0.4
  - 0.65
  frame: 12
  prompt: A cheetah is running on the grass
- bbox_ratios:
  - 0.6
  - 0.35
  - 1.0
  - 0.65
  frame: 18
  prompt: A cheetah is running on the grass
- bbox_ratios:
  - 0.0
  - 0.35
  - 0.4
  - 0.65
  frame: 24
  prompt: A cheetah is running on the grass
num_dd_spatial_steps: 6
num_dd_temporal_steps: 6
seed: 1
spatial_strengthen_scale: 0.1
spatial_weaken_scale: 0.01
temp_strengthen_scale: 0.1
temp_weaken_scale: 0.01
token_inds:
- 1
- 2
trailing_length: 20
