keyframe:
- bbox_ratios:
  - 0.0
  - 0.35
  - 0.25
  - 0.75
  frame: 0
  prompt: an elephant standing on the moon
- bbox_ratios:
  - 0.0
  - 0.35
  - 0.25
  - 0.75
  frame: 18
  prompt: an elephant standing on the moon
- bbox_ratios:
  - 0.75
  - 0.35
  - 1.0
  - 0.75
  frame: 24
  prompt: an elephant running on the moon
token_inds:
- 2
width: 576
height: 320
num_inference_steps:
seed: 2
trailblazer:
  num_dd_spatial_steps: 5
  num_dd_temporal_steps: 5
  spatial_strengthen_scale: 0.175
  spatial_weaken_scale: 0.05
  temp_strengthen_scale: 0.175
  temp_weaken_scale: 0.05
  trailing_length: 15
peekaboo:
  frozen_steps: 2
