keyframe:
- bbox_ratios:
  - 0.0
  - 0.35
  - 0.3
  - 0.75
  frame: 0
  prompt: an astronaut standing on the moon
- bbox_ratios:
  - 0.0
  - 0.35
  - 0.3
  - 0.75
  frame: 18
  prompt: an astronaut standing on the moon
- bbox_ratios:
  - 0.7
  - 0.35
  - 1.0
  - 0.75
  frame: 24
  prompt: an astronaut walking on the moon
num_dd_spatial_steps: 5
num_dd_temporal_steps: 5
num_frames: 24
seed: 123451232531
spatial_strengthen_scale: 0.15
spatial_weaken_scale: 0.001
temp_strengthen_scale: 0.1
temp_weaken_scale: 0.001
token_inds:
- 1
- 2
trailing_length: 11
