keyframe:
- bbox_ratios:
  - 0.0
  - 0.35
  - 0.3
  - 0.65
  frame: 0
  prompt: A white horse galloping on a street
- bbox_ratios:
  - 0.7
  - 0.35
  - 1.0
  - 0.65
  frame: 24
  prompt: A white horse galloping on a street
num_dd_spatial_steps: 5
num_dd_temporal_steps: 5
num_frames: 24
seed: 123451232532
spatial_strengthen_scale: 0.15
spatial_weaken_scale: 0.001
temp_strengthen_scale: 0.15
temp_weaken_scale: 0.001
token_inds:
- 1
- 2
- 3
trailing_length: 16
